services:
  web:
    build: .
    image: server_web
    container_name: web
    hostname: web
    depends_on: 
      - php
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www
      - ./blog:/var/blog
      - ./certificate/:/etc/letsencrypt/
    networks:
      - dmz
  php:
    build: ./php
    image: img_php
    container_name: php
    hostname: php
    depends_on: 
      - db
    volumes:
      - ./www:/var/www
    networks:
      - dmz
      - db_net
  db:
    image: mariadb
    container_name: db
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./my-resolve.cnf:/etc/mysql/conf.d/my-resolve.cnf:ro
      - mariadb_data:/var/lib/mysql
    networks:
      - db_net

networks:
  dmz:
  db_net:

volumes:
  mariadb_data:
