services:
  web:
    build: .
    image: srv_web
    container_name: web
    hostname: web
    depends_on: 
      - php
    ports:
      - 80:80
    volumes:
      - ./www:/var/www
      - ./blog:/var/blog
    networks:
      - dmz
  php:
    build: ./php
    image: img_php
    container_name: php
    hostname: php
    depends_on: 
      - db
    volumes:
      - ./www:/var/www
    networks:
      - dmz
      - db_net
  db:
    image: mariadb
    container_name: db
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - db_net

networks:
  dmz:
  db_net:
